server {
    listen 80;
    server_name calmwarm.nakespro.id;
    root /usr/share/nginx/html/calmwarm;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name modernlight.nakespro.id;
    root /usr/share/nginx/html/modernlight;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name cleanmedical.nakespro.id;
    root /usr/share/nginx/html/cleanmedical;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name friendlycare.nakespro.id;
    root /usr/share/nginx/html/friendlycare;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80 default_server;
    return 404;
}
